# Generated by Django 5.2.8 on 2025-11-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
    ]
